=== ManjuBkmath/WEB_SERVICES/XML/AnimalGroup.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema 
	xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.danielpm1982.com/AnimalGroup"
	xmlns:danielpm1982="http://www.danielpm1982.com/AnimalGroup"
	elementFormDefault="qualified">
	
<!-- 	simple types for elements -->
	<simpleType name="nameType">
		<restriction base="string">
			<maxLength value="20" />
		</restriction>
	</simpleType>
	<simpleType name="speciesType">
		<restriction base="string">
			<enumeration value="Canis familiaris" />
			<enumeration value="Felis catus" />
			<enumeration value="Oryctolagus cuniculus" />
		</restriction>
	</simpleType>
	<simpleType name="color">
		<restriction base="string">
			<maxLength value="20" />
		</restriction>
	</simpleType>
	<simpleType name="birthDate">
		<restriction base="date">
		</restriction>
	</simpleType>
	<simpleType name="owner">
		<restriction base="string">
			<maxLength value="20" />
		</restriction>
	</simpleType>

<!-- 	complex types for elements -->
	<complexType name="animalType">
		<sequence>
			<element name="name" type="danielpm1982:nameType" minOccurs="1" maxOccurs="1" />
			<element name="species" type="danielpm1982:speciesType" minOccurs="1" maxOccurs="1" />
			<element name="color" type="danielpm1982:color" minOccurs="1" maxOccurs="1" />
			<element name="birthDate" type="danielpm1982:birthDate" minOccurs="0" maxOccurs="1" />
			<element name="owner" type="danielpm1982:owner" minOccurs="0" maxOccurs="1" />
		</sequence>
		<attribute ref="danielpm1982:animalId" use="required" />
	</complexType>
	<complexType name="animalGroupType">
		<sequence minOccurs="1" maxOccurs="unbounded">
			<element name="dog" type="danielpm1982:animalType" maxOccurs="unbounded" minOccurs="0" />
			<element name="cat" type="danielpm1982:animalType" maxOccurs="unbounded" minOccurs="0" />
			<element name="rabbit" type="danielpm1982:animalType" maxOccurs="unbounded" minOccurs="0" />
		</sequence>
		<attribute ref="danielpm1982:groupId" use="required" />
	</complexType>

<!-- 	unique attributes for element types	 -->
	<attribute name="animalId" type="int" default="0" />
	<attribute name="groupId" type="int" default="0" />
	
<!-- 	complex root element -->
	<element name="animalGroup" type="danielpm1982:animalGroupType" />
</schema>

<!-- 
base types are from the default namespace, that is, the one without prefix: xmlns="http://www.w3.org/2001/XMLSchema".
extended types or elements are from the target namespace, prefixed as danielpm1982: xmlns:danielpm1982="http://www.danielpm1982.com/Animal".
More about at: https://www.w3schools.com/xml/schema_example.asp . 
-->

=== ManjuBkmath/WEB_SERVICES/XML/AnimalGroup1.xml
<?xml version="1.0" encoding="UTF-8"?>

<danielpm1982:animalGroup
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.danielpm1982.com/AnimalGroup AnimalGroup.xsd"
	xmlns:danielpm1982="http://www.danielpm1982.com/AnimalGroup"
	danielpm1982:groupId="1">
	<danielpm1982:dog danielpm1982:animalId="1">
		<danielpm1982:name>DogA</danielpm1982:name>
		<danielpm1982:species>Canis familiaris</danielpm1982:species>
		<danielpm1982:color>Brown</danielpm1982:color>
		<danielpm1982:birthDate>2005-01-01</danielpm1982:birthDate>
		<danielpm1982:owner>OwnerDEF</danielpm1982:owner>
	</danielpm1982:dog>
	<danielpm1982:cat danielpm1982:animalId="2">
		<danielpm1982:name>CatA</danielpm1982:name>
		<danielpm1982:species>Felis catus</danielpm1982:species>
		<danielpm1982:color>white</danielpm1982:color>
		<danielpm1982:birthDate>2000-01-01</danielpm1982:birthDate>
		<danielpm1982:owner>OwnerABC</danielpm1982:owner>
	</danielpm1982:cat>
	<danielpm1982:cat danielpm1982:animalId="3">
		<danielpm1982:name>CatB</danielpm1982:name>
		<danielpm1982:species>Felis catus</danielpm1982:species>
		<danielpm1982:color>white</danielpm1982:color>
	</danielpm1982:cat>
	<danielpm1982:rabbit danielpm1982:animalId="4">
		<danielpm1982:name>RabbitA</danielpm1982:name>
		<danielpm1982:species>Oryctolagus cuniculus</danielpm1982:species>
		<danielpm1982:color>white</danielpm1982:color>
		<danielpm1982:birthDate>2015-01-01</danielpm1982:birthDate>
		<danielpm1982:owner>OwnerGHI</danielpm1982:owner>
	</danielpm1982:rabbit>
	<danielpm1982:rabbit danielpm1982:animalId="5">
		<danielpm1982:name>RabbitB</danielpm1982:name>
		<danielpm1982:species>Oryctolagus cuniculus</danielpm1982:species>
		<danielpm1982:color>white</danielpm1982:color>
	</danielpm1982:rabbit>
</danielpm1982:animalGroup>

<!-- 
	This is an xml File that represents the data of a Group of Animals (complex type), with a groupId.
	The Group of Animals is composed of any number of Animals, including zero, and each Animal 
	has its own animalId.
  	Each Animal (complex type) is composed, on the other hand, by simple (base) types, some 
  	of these optional (birthDate and owner), others required (name, species and color).
-->

<!-- 
	It's not possible to have more than one root element in an XML file, as the root element represents 
	the whole instance whose data is represented. Only the child elements may vary in min/max occurrences,
	according to the .xsd specification.
	You'd have as many XML files as instances, one for each.
	For example, having 30 groups of animals would demand 30 XML files, for the common XSD Scheme.
-->

<!--
	The namespace (target) used is http://www.danielpm1982.com/AnimalGroup.
	The prefix for that namespace is: danielpm1982.
	And the pointed .xsd file is http://www.danielpm1982.com/AnimalGroup AnimalGroup.xsd.
	
	The .xsd file defines the XML Grammar both for the structure as for the values of each element, 
	attribute and type,	being much more complete and flexible than DTD files.
-->

<!--
For more see: https://www.w3schools.com/xml/default.asp
-->
