=== ManjuBkmath/WEB_SERVICES/XML/ConsultationRecord.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema 
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.danielpm1982.com/consultationRecord"
	xmlns:danielpm1982="http://www.danielpm1982.com/consultationRecord"
	elementFormDefault="qualified">
	
<!-- 	simple types for elements -->
	<xs:simpleType name="nameType">
		<xs:restriction base="xs:string">
			<xs:maxLength value="50" />
			<xs:whiteSpace value="collapse" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="genderType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="male" />
			<xs:enumeration value="female" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="birthDateType">
		<xs:restriction base="xs:date">
			<xs:pattern value="\d{4}-\d{2}-\d{2}" />
			<xs:whiteSpace value="collapse" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="emailType">
		<xs:restriction base="xs:string">
			<xs:maxLength value="50" />
			<xs:whiteSpace value="collapse" />
			<xs:pattern value="([0-9a-zA-Z]([-.\w]*[0-9a-zA-Z])*@([0-9a-zA-Z][-\w]*[0-9a-zA-Z]\.)+[a-zA-Z]{2,9})" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="addressType">
		<xs:restriction base="xs:string">
			<xs:maxLength value="150" />
			<xs:whiteSpace value="collapse" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="phoneNumberType">
		<xs:restriction base="xs:string">
			<xs:maxLength value="20" />
			<xs:whiteSpace value="collapse" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="consultationDateTimeType">
		<xs:restriction base="xs:dateTime" />
	</xs:simpleType>
	<xs:simpleType name="diagnosisType">
		<xs:restriction base="xs:string">
			<xs:maxLength value="500" />
			<xs:whiteSpace value="collapse" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="interventionType">
		<xs:restriction base="xs:string">
			<xs:maxLength value="1000" />
			<xs:whiteSpace value="collapse" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="clinicianType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="pharmacistDoctor" />
			<xs:enumeration value="dentistryDoctor" />
			<xs:enumeration value="psychologistDoctor" />
			<xs:enumeration value="nutritionistDoctor" />
			<xs:enumeration value="physiotherapistDoctor" />
			<xs:enumeration value="physicianDoctor" />
			<xs:enumeration value="otherDoctor" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="clinicianProfessionalNumberType">
		<xs:restriction base="xs:positiveInteger">
			<xs:whiteSpace value="collapse" />
		</xs:restriction>
	</xs:simpleType>
	
<!-- 	unique attributes for element types	 -->
	<xs:attribute name="patientId" type="xs:nonNegativeInteger" default="0" />
	<xs:attribute name="clinicianId" type="xs:nonNegativeInteger" default="0" />
	<xs:attribute name="consultationRecordId" type="xs:nonNegativeInteger" default="0" />

<!-- 	complex types for elements -->
	<xs:complexType name="clinician">
		<xs:sequence>
			<xs:element name="professionalNumber" type="danielpm1982:clinicianProfessionalNumberType" minOccurs="1" maxOccurs="1" />
			<xs:element name="profession" type="danielpm1982:clinicianType" minOccurs="1" maxOccurs="1" />
			<xs:element name="name" type="danielpm1982:nameType" minOccurs="1" maxOccurs="1" />
			<xs:element name="gender" type="danielpm1982:genderType" minOccurs="1" maxOccurs="1" />
			<xs:element name="email" type="danielpm1982:emailType" minOccurs="0" maxOccurs="2" />
			<xs:element name="phoneNumber" type="danielpm1982:phoneNumberType" minOccurs="0" maxOccurs="3" />
		</xs:sequence>
		<xs:attribute ref="danielpm1982:clinicianId" use="required" />
	</xs:complexType>
	<xs:complexType name="patient">
		<xs:sequence>
			<xs:element name="name" type="danielpm1982:nameType" minOccurs="1" maxOccurs="1" />
			<xs:element name="gender" type="danielpm1982:genderType" minOccurs="1" maxOccurs="1" />
			<xs:element name="birthDate" type="danielpm1982:birthDateType" minOccurs="1" maxOccurs="1" />
			<xs:element name="email" type="danielpm1982:emailType" minOccurs="0" maxOccurs="2" />
			<xs:element name="address" type="danielpm1982:addressType" minOccurs="1" maxOccurs="2" />
			<xs:element name="phoneNumber" type="danielpm1982:phoneNumberType" minOccurs="0" maxOccurs="3" />
		</xs:sequence>
		<xs:attribute ref="danielpm1982:patientId" use="required" />
	</xs:complexType>
	<xs:complexType name="consultation">
		<xs:sequence>
			<xs:element name="dateTime" type="danielpm1982:consultationDateTimeType" minOccurs="1" maxOccurs="1" />
			<xs:element name="diagnosis" type="danielpm1982:diagnosisType" minOccurs="1" maxOccurs="unbounded" />
			<xs:element name="intervention" type="danielpm1982:interventionType" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="record">
		<xs:sequence>
			<xs:element name="patient" type="danielpm1982:patient" minOccurs="1" maxOccurs="1" />
			<xs:element name="clinician" type="danielpm1982:clinician" minOccurs="1" maxOccurs="1" />
			<xs:element name="consultation" type="danielpm1982:consultation" minOccurs="1" maxOccurs="1" />
		</xs:sequence>
		<xs:attribute ref="danielpm1982:consultationRecordId" use="required" />
	</xs:complexType>

<!-- 	complex root element -->
	<xs:element name="consultationRecord" type="danielpm1982:record" />
</xs:schema>

<!-- Example of a consultation record XSD schema, against which the XML document instances, for each patient,
validates against. These record instances may be used to create a Health Record system web app (a list of
these records managed by a web app and persisted in a database, for instance), and for transferring these
record data between heterogeneous systems via web services (SOAP or REST).  -->

<!--
For more see:
https://www.w3schools.com/xml/
https://www.w3schools.com/xml/schema_example.asp
-->

=== ManjuBkmath/WEB_SERVICES/XML/ConsultationRecord2.xml
<?xml version="1.0" encoding="UTF-8"?>

<danielpm1982:consultationRecord
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.danielpm1982.com/consultationRecord ConsultationRecord.xsd"
	xmlns:danielpm1982="http://www.danielpm1982.com/consultationRecord"
	danielpm1982:consultationRecordId="1700">
	<danielpm1982:patient danielpm1982:patientId="300">
		<danielpm1982:name>Patient ABC</danielpm1982:name>
		<danielpm1982:gender>male</danielpm1982:gender>
		<danielpm1982:birthDate>1950-10-01</danielpm1982:birthDate>
		<danielpm1982:email>patientabc@patient.com</danielpm1982:email>
		<danielpm1982:address>5th street, 4th neighborhood, city X, state Y, country Z</danielpm1982:address>
		<danielpm1982:phoneNumber>9198165165</danielpm1982:phoneNumber>
		<danielpm1982:phoneNumber>5455454546</danielpm1982:phoneNumber>
	</danielpm1982:patient>
	<danielpm1982:clinician danielpm1982:clinicianId="12">
		<danielpm1982:professionalNumber>3335</danielpm1982:professionalNumber>
		<danielpm1982:profession>pharmacistDoctor</danielpm1982:profession>
		<danielpm1982:name>Pharmacist DEF</danielpm1982:name>
		<danielpm1982:gender>female</danielpm1982:gender>
		<danielpm1982:email>pharmacistdef@clinician.com</danielpm1982:email>
		<danielpm1982:phoneNumber>45657987984</danielpm1982:phoneNumber>
	</danielpm1982:clinician>
	<danielpm1982:consultation>
		<danielpm1982:dateTime>2019-02-05T14:00:00</danielpm1982:dateTime>
		<danielpm1982:diagnosis>Correct diagnosis. New lab pharmaceutical pathology exams solicited and analysed. Good results.</danielpm1982:diagnosis>
		<danielpm1982:diagnosis>Pharmaceutical treatment appropriate, although optimization/individual necessities detected</danielpm1982:diagnosis>
		<danielpm1982:diagnosis>Lack of understanding of the medications</danielpm1982:diagnosis>
		<danielpm1982:diagnosis>Failure to receive the full benefit of prescribed therapy</danielpm1982:diagnosis>
		<danielpm1982:diagnosis>Failure of the patient to adhere to the regimen</danielpm1982:diagnosis>
		<danielpm1982:intervention>New more effective drugs and with new posologies prescribed by the Clinical Pharmacist for better adjustment of pharmacokinetics results, better clinical response and easier adherence from the patient to the treatment</danielpm1982:intervention>
		<danielpm1982:intervention>Pharmaceutical deprescription of no longer needed drugs</danielpm1982:intervention>
		<danielpm1982:intervention>Patient re-oriented about all his conditions, correct care management and pharmaceutical issues related to drugs efficacy and security</danielpm1982:intervention>
		<danielpm1982:intervention>Continuous Clinical Pharmaceutical Consultations scheduled</danielpm1982:intervention>
		<danielpm1982:intervention>All other clinicians notified. No referrals needed.</danielpm1982:intervention>
		<danielpm1982:intervention>Clinical Pharmaceutical consultation documented and registered at the patient Health Record</danielpm1982:intervention>
	</danielpm1982:consultation>
</danielpm1982:consultationRecord>

=== ManjuBkmath/WEB_SERVICES/XML/ConsultationRecord1.xml
<?xml version="1.0" encoding="UTF-8"?>

<danielpm1982:consultationRecord
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.danielpm1982.com/consultationRecord ConsultationRecord.xsd"
	xmlns:danielpm1982="http://www.danielpm1982.com/consultationRecord"
	danielpm1982:consultationRecordId="1500">
	<danielpm1982:patient danielpm1982:patientId="500">
		<danielpm1982:name>Patient ABC</danielpm1982:name>
		<danielpm1982:gender>male</danielpm1982:gender>
		<danielpm1982:birthDate>1950-10-01</danielpm1982:birthDate>
		<danielpm1982:email>patientabc@patient.com</danielpm1982:email>
		<danielpm1982:address>5th street, 4th neighborhood, city X, state Y, country Z</danielpm1982:address>
		<danielpm1982:phoneNumber>9198165165</danielpm1982:phoneNumber>
		<danielpm1982:phoneNumber>5455454546</danielpm1982:phoneNumber>
	</danielpm1982:patient>
	<danielpm1982:clinician danielpm1982:clinicianId="15">
		<danielpm1982:professionalNumber>50430</danielpm1982:professionalNumber>
		<danielpm1982:profession>pharmacistDoctor</danielpm1982:profession>
		<danielpm1982:name>Pharmacist ABC</danielpm1982:name>
		<danielpm1982:gender>male</danielpm1982:gender>
		<danielpm1982:email>pharmacistabc@clinician.com</danielpm1982:email>
		<danielpm1982:phoneNumber>1156189495</danielpm1982:phoneNumber>
	</danielpm1982:clinician>
	<danielpm1982:consultation>
		<danielpm1982:dateTime>2019-01-01T12:00:00</danielpm1982:dateTime>
		<danielpm1982:diagnosis>Wrong diagnosis</danielpm1982:diagnosis>
		<danielpm1982:diagnosis>Wrong Pharmaceutical treatment</danielpm1982:diagnosis>
		<danielpm1982:diagnosis>Medications with no indications</danielpm1982:diagnosis>
		<danielpm1982:diagnosis>Misdiagnosed conditions for which no drug is prescribed</danielpm1982:diagnosis>
		<danielpm1982:diagnosis>Medication prescribed inappropriately for particular conditions</danielpm1982:diagnosis>
		<danielpm1982:diagnosis>Inappropriate dose, dosage form, schedule, route of administration, or method of administration</danielpm1982:diagnosis>
		<danielpm1982:diagnosis>Actual and potential adverse drug events</danielpm1982:diagnosis>
		<danielpm1982:diagnosis>Actual  and  potential  drug–drug,  drug–disease and  drug–nutrient interactions - clinically significant</danielpm1982:diagnosis>
		<danielpm1982:diagnosis>Problems are arising from the financial impact of therapy</danielpm1982:diagnosis>
		<danielpm1982:diagnosis>Lack of understanding of the medications</danielpm1982:diagnosis>
		<danielpm1982:diagnosis>Missing Pharmaceutical clinical pathology lab exams for correct, sensible, specific and specialized histologic, cellular, molecular, genetic and atomic diagnosis</danielpm1982:diagnosis>
		<danielpm1982:intervention>Full pharmaceutical clinical-pathology lab exams solicited and analysed by the Pathologist Pharmacist along with the Clinical Pharmacist</danielpm1982:intervention>
		<danielpm1982:intervention>New diagnosis consensus reached along with the clinical care team</danielpm1982:intervention>
		<danielpm1982:intervention>New pharmacotherapy plan established and prescribed by the Clinical Pharmacist, new clinical protocols and patient categories adopted</danielpm1982:intervention>
		<danielpm1982:intervention>All drug-related problems regarding indication, missing drugs and posology corrected</danielpm1982:intervention>
		<danielpm1982:intervention>Drug events managed and interactions resolved</danielpm1982:intervention>
		<danielpm1982:intervention>Financial problem resolved, with costs reduced by 50%</danielpm1982:intervention>
		<danielpm1982:intervention>Patient re-oriented about all his conditions, correct care management and pharmaceutical issues related to drugs efficacy and security</danielpm1982:intervention>
		<danielpm1982:intervention>Continuous Clinical Pharmaceutical Consultations established and scheduled</danielpm1982:intervention>
		<danielpm1982:intervention>All other clinicians notified and re-scheduled for the respective re-consultations</danielpm1982:intervention>
		<danielpm1982:intervention>Clinical Pharmaceutical consultation documented and registered at the patient Health Record</danielpm1982:intervention>
	</danielpm1982:consultation>
</danielpm1982:consultationRecord>
