=== ManjuBkmath/WEB_SERVICES/XML/EmailNamedTypesMethod.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema 
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.danielpm1982.com/EmailNamedTypesMethod"
	xmlns:danielpm1982="http://www.danielpm1982.com/EmailNamedTypesMethod"
	elementFormDefault="qualified">
	<!--Definition of base simple named types with restrictions -->
	<xs:simpleType name="stringType">
		<xs:restriction base="xs:string">
			<xs:maxLength value="50" />
			<xs:whiteSpace value="collapse" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="stringBigType">
		<xs:restriction base="xs:string">
			<xs:maxLength value="1000000" />
			<xs:whiteSpace value="collapse" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="longType">
		<xs:restriction base="xs:long" />
	</xs:simpleType>
	<xs:simpleType name="dateTimeType">
		<xs:restriction base="xs:dateTime" />
	</xs:simpleType>
	<xs:simpleType name="emailType">
		<xs:restriction base="xs:string">
			<xs:maxLength value="50" />
			<xs:whiteSpace value="collapse" />
			<xs:pattern value="([0-9a-zA-Z]([-.\w]*[0-9a-zA-Z])*@([0-9a-zA-Z][-\w]*[0-9a-zA-Z]\.)+[a-zA-Z]{2,9})" />
		</xs:restriction>
	</xs:simpleType>
	<!--Definition of base complex named types with simple elements, attributes and simple named types -->
	<xs:complexType name="emailTo">
	  	<xs:sequence>
		    <xs:element name="name" type="danielpm1982:stringType" />
		    <xs:element name="email" type="danielpm1982:emailType" />
	  	</xs:sequence>
	</xs:complexType>
	<xs:complexType name="emailFrom">
	  	<xs:sequence>
		    <xs:element name="name" type="danielpm1982:stringType" />
		    <xs:element name="email" type="danielpm1982:emailType" />
	  	</xs:sequence>
	</xs:complexType>
	<xs:complexType name="email">
	  	<xs:sequence>
		    <xs:element name="from" type="danielpm1982:emailFrom" />
		    <xs:element name="to" type="danielpm1982:emailTo" />
		    <xs:element name="dateTime" type="danielpm1982:dateTimeType" />
		    <xs:element name="text" type="danielpm1982:stringBigType" />
	  	</xs:sequence>
	  	<xs:attribute name="emailId" type="danielpm1982:longType" use="required" />
	</xs:complexType>
	<!--Definition of the root element using previously defined simple and complex named types (including all nested elements, attributes and named types) -->
	<xs:element name="email" type="danielpm1982:email" />
</xs:schema>

=== ManjuBkmath/WEB_SERVICES/XML/Email.xml
<?xml version="1.0" encoding="UTF-8"?>
<danielpm1982:email
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.danielpm1982.com/EmailNamedTypesMethod EmailNamedTypesMethod.xsd"
	xmlns:danielpm1982="http://www.danielpm1982.com/EmailNamedTypesMethod"
	emailId="100">
	<danielpm1982:from>
		<danielpm1982:name>name1name1name1name1name1name1name1name1name1name1</danielpm1982:name>
		<danielpm1982:email>name1@name.com</danielpm1982:email>
	</danielpm1982:from>
	<danielpm1982:to>
		<danielpm1982:name>name2name2name2name2name2name2name2name2name2name2</danielpm1982:name>
		<danielpm1982:email>name2@name.com</danielpm1982:email>
	</danielpm1982:to>
	<danielpm1982:dateTime>2019-12-01T16:00:00</danielpm1982:dateTime>
	<danielpm1982:text>Hello World! Hello World! Hello World! Hello World!
		Hello World! Hello World! Hello World! Hello World! Hello World! Hello
		World! Hello World! Hello World! Hello World! Hello World! Hello
		World! Hello World! Hello World! Hello World! Hello World! Hello
		World! Hello World! Hello World! Hello World! Hello World! Hello
		World! Hello World! Hello World! Hello World! Hello World! Hello
		World! Hello World! Hello World! Hello World! Hello World! Hello
		World! Hello World! Hello World! Hello World! Hello World! Hello
		World! Hello World! Hello World! Hello World! Hello World! Hello
		World! Hello World! Hello World! Hello World! Hello World! Hello
		World! Hello World! Hello World! Hello World! Hello World! Hello
		World! Hello World! Hello World! Hello World! Hello World! Hello
		World! Hello World! Hello World! Hello World! Hello World! Hello
		World! Hello World! Hello World! Hello World! Hello World! Hello
		World! Hello World! Hello World! Hello World! Hello World! Hello
		World! Hello World! Hello World! Hello World! Hello World! Hello
		World! Hello World! Hello World! Hello World! Hello World! Hello
		World! Hello World! Hello World! Hello World! Hello World! Hello
		World! Hello World! Hello World! Hello World! Hello World!</danielpm1982:text>
</danielpm1982:email>
