=== ManjuBkmath/WEB_SERVICES/XML/ShipOrderNamedTypesMethodIndicators.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema 
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.danielpm1982.com/ShipOrderNamedTypesMethodIndicators"
	xmlns:danielpm1982="http://www.danielpm1982.com/ShipOrderNamedTypesMethodIndicators"
	elementFormDefault="qualified">
	<xs:simpleType name="stringType">
		<xs:restriction base="xs:string" />
	</xs:simpleType>
	<xs:simpleType name="booleanType">
		<xs:restriction base="xs:boolean" />
	</xs:simpleType>
	<xs:simpleType name="intType">
	  	<xs:restriction base="xs:positiveInteger" />
	</xs:simpleType>
	<xs:simpleType name="decType">
	  	<xs:restriction base="xs:decimal" />
	</xs:simpleType>
	<xs:simpleType name="dateTimeType">
		<xs:restriction base="xs:dateTime" />
	</xs:simpleType>
	<xs:complexType name="shipToType">
<!-- The <all> indicator specifies that the child elements can appear in any order, and that each child element must occur at most once (minOccurs can be 0 or 1; maxOccurs can only be 1). The occurrence number for the "all" set itself, can only be 1 (at least and at most).-->
		<xs:all minOccurs="1" maxOccurs="1">
		    <xs:element name="name" type="danielpm1982:stringType" minOccurs="1" maxOccurs="1" />
		    <xs:element name="address" type="danielpm1982:stringType" minOccurs="1" />
		    <xs:element name="email" type="danielpm1982:stringType" minOccurs="1" />
		    <xs:element name="city" type="danielpm1982:stringType" minOccurs="1" />
		    <xs:element name="state" type="danielpm1982:stringType" minOccurs="0" />
		    <xs:element name="country" type="danielpm1982:stringType" minOccurs="1" />
		    <xs:element name="zipCode" type="danielpm1982:intType" minOccurs="0" />
		</xs:all>
	</xs:complexType>
	<xs:complexType name="serviceType">
<!-- The <choice> indicator specifies that either one child element or another can occur (0 or more times), not both, or not more than one different child element at the same instance (except if multiple choices are set, by default at least and at most one choice is set). MaxOccurs define the maximum number of times the choice can occur (>=0, or "unbounded") - default value is 1. MinOccurs define the minimum number of times the choice can occur (>=0) - default value is 1. If only one choice is allowed, at most one of the elements could be chosen (occurrence of 0 or more), but if multiple choices are set, then more than one of the child elements could occur, each with an occurrence of 0 or more on every choice.-->
		<xs:choice minOccurs="0" maxOccurs="1">
			<xs:element name="priorityMailExpress" type="danielpm1982:stringType" />
			<xs:element name="priorityMail" type="danielpm1982:stringType" />
			<xs:element name="firstClassMail" type="danielpm1982:stringType" />
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="itemType">
	  	<xs:all minOccurs="1" maxOccurs="1">
		    <xs:element name="title" type="danielpm1982:stringType" minOccurs="1" maxOccurs="1" />
		    <xs:element name="quantity" type="danielpm1982:intType" minOccurs="1" />
		    <xs:element name="price" type="danielpm1982:decType" minOccurs="0" />
	  	</xs:all>
	</xs:complexType>
<!-- The <group> indicator is used to define related sets of elements. You must define an all, choice, or sequence element inside the group declaration. After you have defined a group, you can reference it in another definition, using the "ref" attribute, as if you were declaring all elements there, as usual. It favors modularization and reuse of the XSD code components (tags). -->
	<xs:group name="clientDataGroup">
		<xs:sequence>
			<xs:element name="client" type="danielpm1982:stringType" maxOccurs="1" />
	    	<xs:element name="shipTo" type="danielpm1982:shipToType" maxOccurs="1" />
		</xs:sequence>
	</xs:group>
	<xs:group name="itemServiceDataGroup">
		<xs:sequence>
			<xs:element name="service" type="danielpm1982:serviceType" maxOccurs="1" />
		    <xs:element name="item" type="danielpm1982:itemType" maxOccurs="unbounded" />
		    <xs:element name="discountTicket" type="danielpm1982:stringType" maxOccurs="1" />
		</xs:sequence>
	</xs:group>
<!-- The <attributeGroup> defines groups of attributes, with no need of any other nested indicator (all, choice or sequence). After you have defined an attribute group, you can reference it in another definition using the "ref" attribute. As with <group>, it favors modularization and reuse of the XSD code components (tags). -->
	<xs:attributeGroup name="shipOrderAttributesGroup">
		<xs:attribute name="orderId" type="danielpm1982:stringType" use="required" />
		<xs:attribute name="orderPayed" type="danielpm1982:booleanType" use="optional" />
		<xs:attribute name="orderProcessed" type="danielpm1982:booleanType" use="optional" />
		<xs:attribute name="orderShipped" type="danielpm1982:booleanType" use="optional" />
		<xs:attribute name="orderDelivered" type="danielpm1982:booleanType" use="optional" />
	</xs:attributeGroup>
	<xs:complexType name="shipOrderListType">
<!-- The <sequence> indicator specifies that the child elements must appear in a specific order, independently from the min or max occurrence of each element. If maxOccurs is set at the sequence (>=0), and if multiple sequences are allowed, then more than one sequence could appear, but with its child elements always respecting the order (despite their individual occurrence number) - default is 1. If minOccurs is set at the sequence, it defines the minimum number of times the sequence can occur (>=0). To specify that this sequence group is optional, set this attribute to zero - default is 1. For the child elements of the sequence, the occurrences can be set individually (>=0).-->
  		<xs:sequence minOccurs="1" maxOccurs="unbounded">
  			<xs:group ref="danielpm1982:clientDataGroup" maxOccurs="1" />
  			<xs:group ref="danielpm1982:itemServiceDataGroup" maxOccurs="1" />
  			<xs:element name="dateTime" type="danielpm1982:dateTimeType" minOccurs="1" maxOccurs="1" />	
  		</xs:sequence>
  		<xs:attributeGroup ref="danielpm1982:shipOrderAttributesGroup" />
	</xs:complexType>
	<xs:element name="shipOrderList" type="danielpm1982:shipOrderListType" />
</xs:schema>

=== ManjuBkmath/WEB_SERVICES/XML/ShipOrderNamedTypesMethodIndicators.xml
<?xml version="1.0" encoding="UTF-8"?>
<danielpm1982:shipOrderList
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.danielpm1982.com/ShipOrderNamedTypesMethodIndicators ShipOrderNamedTypesMethodIndicators.xsd"
	xmlns:danielpm1982="http://www.danielpm1982.com/ShipOrderNamedTypesMethodIndicators"
	danielpm1982:orderListId="1">
	<danielpm1982:shipOrder
		danielpm1982:orderId="505" danielpm1982:orderProcessed="true"
		danielpm1982:orderPayed="true" danielpm1982:orderShipped="true"
		danielpm1982:orderDelivered="false">
		<danielpm1982:client>client1</danielpm1982:client>
		<danielpm1982:shipTo>
			<danielpm1982:name>person1</danielpm1982:name>
			<danielpm1982:address>person1Address</danielpm1982:address>
			<danielpm1982:email>person1Email</danielpm1982:email>
			<danielpm1982:city>person1City</danielpm1982:city>
			<danielpm1982:state>person1State</danielpm1982:state>
			<danielpm1982:country>person1Country</danielpm1982:country>
			<danielpm1982:zipCode>60000000</danielpm1982:zipCode>
		</danielpm1982:shipTo>
		<danielpm1982:service>
			<danielpm1982:firstClassMail>true</danielpm1982:firstClassMail>
		</danielpm1982:service>
		<danielpm1982:item>
			<danielpm1982:title>item1</danielpm1982:title>
			<danielpm1982:quantity>5</danielpm1982:quantity>
			<danielpm1982:price>10.0</danielpm1982:price>
		</danielpm1982:item>
		<danielpm1982:item>
			<danielpm1982:title>item2</danielpm1982:title>
			<danielpm1982:quantity>15</danielpm1982:quantity>
			<danielpm1982:price>20.5</danielpm1982:price>
		</danielpm1982:item>
		<danielpm1982:item>
			<danielpm1982:title>item3</danielpm1982:title>
			<danielpm1982:quantity>20</danielpm1982:quantity>
			<danielpm1982:price>5.9</danielpm1982:price>
		</danielpm1982:item>
		<danielpm1982:discountTicket>DISCOUNT_TICKET_20</danielpm1982:discountTicket>
		<danielpm1982:dateTime>2019-10-19T15:00:00</danielpm1982:dateTime>
	</danielpm1982:shipOrder>
	<danielpm1982:shipOrder
		danielpm1982:orderId="802"
		danielpm1982:orderProcessed="true"
		danielpm1982:orderPayed="false"
		danielpm1982:orderShipped="false"
		danielpm1982:orderDelivered="false">
		<danielpm1982:client>client1</danielpm1982:client>
		<danielpm1982:shipTo>
			<danielpm1982:name>person2</danielpm1982:name>
			<danielpm1982:address>person2Address</danielpm1982:address>
			<danielpm1982:email>person2Email</danielpm1982:email>
			<danielpm1982:city>person2City</danielpm1982:city>
			<danielpm1982:state>person2State</danielpm1982:state>
			<danielpm1982:country>person2Country</danielpm1982:country>
			<danielpm1982:zipCode>60000000</danielpm1982:zipCode>
		</danielpm1982:shipTo>
		<danielpm1982:service>
			<danielpm1982:priorityMailExpress>true</danielpm1982:priorityMailExpress>
		</danielpm1982:service>
		<danielpm1982:item>
			<danielpm1982:title>item4</danielpm1982:title>
			<danielpm1982:quantity>3</danielpm1982:quantity>
			<danielpm1982:price>20.0</danielpm1982:price>
		</danielpm1982:item>
		<danielpm1982:item>
			<danielpm1982:title>item5</danielpm1982:title>
			<danielpm1982:quantity>1</danielpm1982:quantity>
			<danielpm1982:price>90.5</danielpm1982:price>
		</danielpm1982:item>
		<danielpm1982:discountTicket>DISCOUNT_TICKET_50</danielpm1982:discountTicket>
		<danielpm1982:dateTime>2019-10-19T16:00:00</danielpm1982:dateTime>
	</danielpm1982:shipOrder>
</danielpm1982:shipOrderList>
