=== ManjuBkmath/WEB_SERVICES/XML/ShipOrderNamedTypesMethod.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema 
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.danielpm1982.com/ShipOrderNamedTypesMethod"
	xmlns:danielpm1982="http://www.danielpm1982.com/ShipOrderNamedTypesMethod"
	elementFormDefault="qualified">
	<!--Definition of base simple named types with restrictions -->
	<xs:simpleType name="stringType">
		<xs:restriction base="xs:string" />
	</xs:simpleType>
	<xs:simpleType name="intType">
	  	<xs:restriction base="xs:positiveInteger" />
	</xs:simpleType>
	<xs:simpleType name="decType">
	  	<xs:restriction base="xs:decimal" />
	</xs:simpleType>
	<xs:simpleType name="dateTimeType">
		<xs:restriction base="xs:dateTime" />
	</xs:simpleType>
	<!--Definition of base complex named types with simple elements, attributes and simple named types -->
	<xs:complexType name="shipToType">
	  	<xs:sequence>
		    <xs:element name="name" type="danielpm1982:stringType" />
		    <xs:element name="address" type="danielpm1982:stringType" />
		    <xs:element name="email" type="danielpm1982:stringType" />
		    <xs:element name="city" type="danielpm1982:stringType" />
		    <xs:element name="state" type="danielpm1982:stringType" />
		    <xs:element name="country" type="danielpm1982:stringType" />
		    <xs:element name="zipCode" type="danielpm1982:intType" />
	  </xs:sequence>
	</xs:complexType>
	<xs:complexType name="itemType">
	  	<xs:sequence>
		    <xs:element name="title" type="danielpm1982:stringType" />
		    <xs:element name="quantity" type="danielpm1982:intType" />
		    <xs:element name="price" type="danielpm1982:decType" />
	  	</xs:sequence>
	</xs:complexType>
	<xs:complexType name="shipOrderType">
	  	<xs:sequence>
		    <xs:element name="client" type="danielpm1982:stringType" />
		    <xs:element name="shipTo" type="danielpm1982:shipToType" />
		    <xs:element name="item" maxOccurs="unbounded" type="danielpm1982:itemType" />
		    <xs:element name="discountTicket" type="danielpm1982:stringType" />
		    <xs:element name="dateTime" type="danielpm1982:dateTimeType" />
	  	</xs:sequence>
	  	<xs:attribute name="orderId" type="danielpm1982:stringType" use="required" />
	</xs:complexType>
	<!--Definition of the root element using previously defined simple and complex named types (including all nested elements, attributes and named types) -->
	<xs:element name="shipOrder" type="danielpm1982:shipOrderType" />
</xs:schema>

=== ManjuBkmath/WEB_SERVICES/XML/ShipOrderNamedTypesMethod.xml
<?xml version="1.0" encoding="UTF-8"?>
<danielpm1982:shipOrder 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.danielpm1982.com/ShipOrderNamedTypesMethod ShipOrderNamedTypesMethod.xsd"
	xmlns:danielpm1982="http://www.danielpm1982.com/ShipOrderNamedTypesMethod"
	danielpm1982:orderId="100">
	<danielpm1982:client>client1</danielpm1982:client>
	<danielpm1982:shipTo>
		<danielpm1982:name>client1Name</danielpm1982:name>
		<danielpm1982:address>client1Address</danielpm1982:address>
		<danielpm1982:email>client1Email</danielpm1982:email>
		<danielpm1982:city>client1City</danielpm1982:city>
		<danielpm1982:state>client1State</danielpm1982:state>
		<danielpm1982:country>client1Country</danielpm1982:country>
		<danielpm1982:zipCode>60000000</danielpm1982:zipCode>
	</danielpm1982:shipTo>
	<danielpm1982:item>
		<danielpm1982:title>item1</danielpm1982:title>
		<danielpm1982:quantity>5</danielpm1982:quantity>
		<danielpm1982:price>100.5</danielpm1982:price>
	</danielpm1982:item>
	<danielpm1982:item>
		<danielpm1982:title>item2</danielpm1982:title>
		<danielpm1982:quantity>20</danielpm1982:quantity>
		<danielpm1982:price>65.9</danielpm1982:price>
	</danielpm1982:item>
	<danielpm1982:item>
		<danielpm1982:title>item3</danielpm1982:title>
		<danielpm1982:quantity>3</danielpm1982:quantity>
		<danielpm1982:price>3500.5</danielpm1982:price>
	</danielpm1982:item>
	<danielpm1982:discountTicket>DISCOUNT_TICKET_20</danielpm1982:discountTicket>
	<danielpm1982:dateTime>2019-10-19T16:00:00</danielpm1982:dateTime>
</danielpm1982:shipOrder>
